//! Generated programs through the rule-6 harness (method.md rule 5,
//! compiler.md §5): each program `fibgen` generates is written as a
//! case whose header is the model's verdict, the result it computes
//! or the trap it predicts, then run interpreted and compiled and
//! judged like a case of the suite. A program the model cannot
//! evaluate is the generator's own gap: counted, not run.

use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};

use fibgen::model::ModelError;
use fibgen::{gen, model, print};
use fibref::cases::{CaseResult, Report, Status};

use super::Harness;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenConfig {
    /// The first seed; program `i` has seed `seed + i`.
    pub seed: u64,
    pub count: usize,
    /// One size for every program, or sizes 1 to 6 in turn, as
    /// `fibgen run` assigns them, so `fibgen show` reproduces any of
    /// them.
    pub size: Option<u32>,
    pub jobs: usize,
    /// Where the programs are written. A passing program's file is
    /// removed; any other is kept for `fibc run` and `fibgen show`.
    pub dir: PathBuf,
}

pub struct GenReport {
    pub report: Report,
    /// The programs the model could not evaluate, as (seed, size).
    pub model_gaps: Vec<(u64, u32)>,
}

/// The size of program `i` (fibgen `driver::size_of`).
pub fn size_of(cfg: &GenConfig, i: usize) -> u32 {
    cfg.size.unwrap_or(1 + (i % 6) as u32)
}

/// The case header the model's verdict gives, or `None` for a gap.
fn header(seed: u64, size: u32, expected: &Result<i64, ModelError>) -> Option<String> {
    let verdict = match expected {
        Ok(n) => format!(";; expect: accept\n;; result: {n}\n;; audit:  clean\n"),
        Err(ModelError::Trap(m)) => format!(";; expect: trap\n;; trap:   {m}\n"),
        Err(_) => return None,
    };
    Some(format!(
        ";; spec:   method.md rule 5 (fibgen show --seed {seed} --size {size})\n{verdict};; Generated by fibgen; the header is its model's verdict.\n\n"
    ))
}

/// Generates and runs `cfg.count` programs on `cfg.jobs` threads.
pub fn run(harness: &Harness, cfg: &GenConfig) -> std::io::Result<GenReport> {
    std::fs::create_dir_all(&cfg.dir)?;
    let next = AtomicUsize::new(0);
    let (mut results, mut model_gaps) = (Vec::new(), Vec::new());
    std::thread::scope(|scope| {
        let workers: Vec<_> = (0..cfg.jobs.max(1))
            .map(|_| {
                scope.spawn(|| {
                    let (mut rs, mut gaps) = (Vec::new(), Vec::new());
                    loop {
                        let i = next.fetch_add(1, Ordering::Relaxed);
                        if i >= cfg.count {
                            return (rs, gaps);
                        }
                        let (seed, size) = (cfg.seed + i as u64, size_of(cfg, i));
                        match one(harness, cfg, seed, size) {
                            Some(r) => rs.push(r),
                            None => gaps.push((seed, size)),
                        }
                    }
                })
            })
            .collect();
        for w in workers {
            match w.join() {
                Ok((rs, gaps)) => {
                    results.extend(rs);
                    model_gaps.extend(gaps);
                }
                Err(_) => {
                    eprintln!("fibc gen: a worker thread panicked; its programs are not counted")
                }
            }
        }
    });
    results.sort_by(|a, b| a.path.cmp(&b.path));
    model_gaps.sort_unstable();
    Ok(GenReport {
        report: Report::from_results(results),
        model_gaps,
    })
}

/// One program as a case file, run both ways and judged; `None` for a
/// model gap. A file that cannot be written is judged unreadable by
/// the harness, which is a header error, never a pass.
fn one(harness: &Harness, cfg: &GenConfig, seed: u64, size: u32) -> Option<CaseResult> {
    let p = gen::generate(seed, size);
    let head = header(seed, size, &model::expected(&p))?;
    let path = cfg.dir.join(format!("gen-{seed:08}-{size}.fib"));
    let _ = std::fs::write(&path, format!("{head}{}", print::program(&p)));
    let r = harness.run_case(&path);
    if matches!(r.status, Status::Pass) {
        let _ = std::fs::remove_file(&path);
    }
    Some(r)
}

#[cfg(test)]
mod tests {
    use super::*;
    use fibref::cases::{parse_header, AuditExpect, Expected, Verdict};
    use std::path::Path;

    #[test]
    fn the_header_is_the_models_verdict() {
        let h = header(7, 2, &Ok(3)).expect("a result");
        let parsed = parse_header(Path::new("x.fib"), &h).expect("parses");
        assert_eq!(
            parsed.verdict,
            Verdict::Accept {
                result: Expected::Int(3),
                audit: AuditExpect::Clean,
                allocs: None,
            }
        );
        let h = header(7, 2, &Err(ModelError::Trap("integer / by zero".into()))).expect("a trap");
        let parsed = parse_header(Path::new("x.fib"), &h).expect("parses");
        assert_eq!(
            parsed.verdict,
            Verdict::Trap {
                trap: "integer / by zero".into()
            }
        );
        assert!(header(7, 2, &Err(ModelError::Budget)).is_none());
    }

    #[test]
    fn sizes_run_1_to_6_in_turn_unless_fixed() {
        let cfg = |size| GenConfig {
            seed: 1,
            count: 0,
            size,
            jobs: 1,
            dir: PathBuf::new(),
        };
        let turns: Vec<u32> = (0..8).map(|i| size_of(&cfg(None), i)).collect();
        assert_eq!(turns, [1, 2, 3, 4, 5, 6, 1, 2]);
        assert_eq!(size_of(&cfg(Some(4)), 9), 4);
    }
}
