//! `fibgen`: generate random well-typed fibber programs, run each through
//! the reference interpreter and its memory audit, compare the result
//! with an independent model, and minimise what fails (spec/method.md,
//! rule 5).

#![forbid(unsafe_code)]

use std::path::PathBuf;
use std::process::ExitCode;
use std::time::Duration;

use fibgen::driver::{minimise, run_batch, Config, Sample, Summary};
use fibgen::report::{write_case, Finding};
use fibgen::run::Class;
use fibgen::{gen, model, print};

const USAGE: &str = "usage:
  fibgen run --seed S --count N [--size K] [--jobs J] [--timeout SECS]
             [--no-shrink] [--shrink-budget R] [--exemplars E] [--write DIR]
      generate N programs from seeds S.. (size K, or sizes 1..=6 in turn),
      run each through fibref, print the tallies, the distinct failures and
      the coverage; minimise one program per distinct finding and, with
      --write, write it to DIR (cases/found/generated by convention)
  fibgen show --seed S [--size K]
      print the program for seed S and the result the model expects";

/// Parsed options.
struct Opts {
    cmd: String,
    cfg: Config,
    write: Option<PathBuf>,
}

fn parse(args: &[String]) -> Result<Opts, String> {
    let cmd = args.first().cloned().ok_or("no command")?;
    let mut cfg = Config {
        seed: 1,
        count: 100,
        size: None,
        jobs: std::thread::available_parallelism().map_or(2, |n| n.get()),
        timeout: Duration::from_secs(20),
        shrink: true,
        shrink_budget: 1500,
        exemplars: 1,
    };
    let mut write = None;
    let mut it = args[1..].iter();
    while let Some(flag) = it.next() {
        if flag == "--no-shrink" {
            cfg.shrink = false;
            continue;
        }
        let val = it.next().ok_or(format!("{flag} needs a value"))?;
        let num = || val.parse::<u64>().map_err(|e| format!("{flag} {val}: {e}"));
        match flag.as_str() {
            "--seed" => cfg.seed = num()?,
            "--count" => cfg.count = num()? as usize,
            "--size" => cfg.size = Some(num()? as u32),
            "--jobs" => cfg.jobs = num()? as usize,
            "--timeout" => cfg.timeout = Duration::from_secs(num()?),
            "--shrink-budget" => cfg.shrink_budget = num()? as usize,
            "--exemplars" => cfg.exemplars = num()? as usize,
            "--write" => write = Some(PathBuf::from(val)),
            _ => return Err(format!("unknown option {flag}")),
        }
    }
    Ok(Opts { cmd, cfg, write })
}

fn show(cfg: &Config) {
    let p = gen::generate(cfg.seed, cfg.size.unwrap_or(3));
    print!("{}", print::program(&p));
    println!(";; model: {:?}", model::expected(&p));
}

fn print_summary(s: &Summary, cfg: &Config) {
    let total: usize = s.tallies.values().sum();
    println!(
        "fibgen: {total} programs, seeds {}..{}, sizes {}, {} jobs, wall time {:.1} s",
        cfg.seed,
        cfg.seed + cfg.count as u64 - 1,
        cfg.size
            .map_or("1..=6 in turn".to_string(), |k| k.to_string()),
        cfg.jobs,
        s.elapsed.as_secs_f64()
    );
    for (class, n) in &s.tallies {
        println!("  {:<28} {n}", class.label());
    }
    println!("\ndistinct outcomes other than ok (count, first seed/size, key):");
    for ((class, key), (n, samples)) in &s.groups {
        let (seed, size) = samples.first().map_or((0, 0), |x| (x.seed, x.size));
        println!(
            "  {:<28} {n:>6}  seed {seed} size {size}  {key}",
            class.label()
        );
    }
    println!("\ncoverage:\n{}", s.coverage.render());
}

fn report_groups(s: &Summary, cfg: &Config, write: &Option<PathBuf>) {
    for ((class, key), (_, samples)) in &s.groups {
        if !class.is_finding() && *class != Class::Rejected {
            continue;
        }
        for sample in samples {
            report_one(cfg, *class, key, sample, write);
        }
    }
}

fn report_one(cfg: &Config, class: Class, key: &str, sample: &Sample, write: &Option<PathBuf>) {
    let (small, verdict, exp) = minimise(sample, cfg);
    let source = print::program(&small);
    println!(
        "==== {} [{key}] seed {} size {}",
        class.label(),
        sample.seed,
        sample.size
    );
    println!(
        ";; minimised: {} ({}), model {exp}",
        verdict.class.label(),
        verdict.detail
    );
    print!("{source}");
    if !class.is_finding() {
        return;
    }
    let Some(dir) = write else { return };
    let finding = Finding {
        seed: sample.seed,
        size: sample.size,
        expected: exp,
        observed: &verdict,
        source: &source,
    };
    match write_case(dir, &finding) {
        Ok(path) => println!(";; written to {}", path.display()),
        Err(e) => eprintln!("fibgen: cannot write the case to {}: {e}", dir.display()),
    }
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let opts = match parse(&args) {
        Ok(o) => o,
        Err(e) => {
            eprintln!("fibgen: {e}\n{USAGE}");
            return ExitCode::from(2);
        }
    };
    match opts.cmd.as_str() {
        "show" => show(&opts.cfg),
        "run" => {
            let summary = run_batch(&opts.cfg);
            print_summary(&summary, &opts.cfg);
            report_groups(&summary, &opts.cfg, &opts.write);
            let findings = summary
                .tallies
                .iter()
                .any(|(c, n)| c.is_finding() && *n > 0);
            return if findings {
                ExitCode::from(1)
            } else {
                ExitCode::SUCCESS
            };
        }
        _ => {
            eprintln!("{USAGE}");
            return ExitCode::from(2);
        }
    }
    ExitCode::SUCCESS
}
