//! Writing a minimised finding as a case file in the format of
//! `cases/ownership/README.md`.

use std::io;
use std::path::{Path, PathBuf};

use crate::run::Verdict;

/// What a case file records about one finding.
pub struct Finding<'a> {
    /// The seed of the original program.
    pub seed: u64,
    /// Its size.
    pub size: u32,
    /// The verdict the spec requires: the model's result.
    pub expected: i64,
    /// What the interpreter did with the minimised program.
    pub observed: &'a Verdict,
    /// The minimised program's source.
    pub source: &'a str,
}

/// Words of a key that say nothing about the failure.
const NOISE: [&str; 8] = [
    "audit", "error", "id", "objid", "n", "finding", "scopeid", "op",
];

/// A file-name slug for a verdict: its class, then the first words of
/// its key that say something, lower case, letters and digits only.
pub fn slug(v: &Verdict) -> String {
    let label = v.class.label().to_lowercase();
    let label = label.strip_prefix("finding ").unwrap_or(&label).to_string();
    let key = v.key.to_lowercase();
    let words = key
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty() && !NOISE.contains(w))
        .take(6);
    let mut out: Vec<String> = label.split(' ').map(str::to_string).collect();
    out.extend(words.map(str::to_string));
    out.join("-")
}

/// The next free `NNN` in `dir`.
fn next_number(dir: &Path) -> io::Result<u32> {
    let mut max = 0;
    for entry in std::fs::read_dir(dir)? {
        let name = entry?.file_name().to_string_lossy().to_string();
        if let Some(n) = name.get(..3).and_then(|p| p.parse::<u32>().ok()) {
            max = max.max(n);
        }
    }
    Ok(max + 1)
}

/// The text of the case file.
pub fn case_text(f: &Finding) -> String {
    let mut out = String::new();
    out.push_str(";; spec:   method.md rule 5; ownership.md §1-§8 (generated program)\n");
    out.push_str(";; expect: accept\n");
    out.push_str(&format!(";; result: {}\n", f.expected));
    out.push_str(";; audit:  clean\n");
    out.push_str(";; Generated by fibgen (spec/method.md rule 5) and minimised: the\n");
    out.push_str(&format!(
        ";; original is `fibgen show --seed {} --size {}`.\n",
        f.seed, f.size
    ));
    out.push_str(";; The program is well-typed and ownership-legal by construction, so\n");
    out.push_str(";; the spec requires accept, the model's result and a clean audit.\n");
    out.push_str(&format!(
        ";; Observed (fibref): {}\n",
        f.observed.class.label()
    ));
    for line in f.observed.detail.lines() {
        out.push_str(&format!(";;   {line}\n"));
    }
    out.push('\n');
    out.push_str(f.source);
    out
}

/// Writes the case to `dir/NNN-<slug>.fib` and returns its path.
pub fn write_case(dir: &Path, f: &Finding) -> io::Result<PathBuf> {
    std::fs::create_dir_all(dir)?;
    let n = next_number(dir)?;
    let path = dir.join(format!("{n:03}-{}.fib", slug(f.observed)));
    std::fs::write(&path, case_text(f))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::run::Class;

    fn verdict() -> Verdict {
        Verdict {
            class: Class::AuditFailure,
            key: "audit: leak".into(),
            detail: "result 3, audit clean=false leak-cycles=0 leaks=1 errors=0".into(),
        }
    }

    #[test]
    fn slug_is_file_safe() {
        assert_eq!(slug(&verdict()), "audit-failure-leak");
        let uaf = Verdict {
            class: Class::RunFailed,
            key: "audit error: UseAfterFree { id: ObjId(N), op: Read }".into(),
            detail: String::new(),
        };
        assert_eq!(slug(&uaf), "run-failed-useafterfree-read");
    }

    #[test]
    fn case_text_has_a_parseable_accept_header() {
        let v = verdict();
        let text = case_text(&Finding {
            seed: 9,
            size: 2,
            expected: 3,
            observed: &v,
            source: "(defun main () -> i64 3)\n",
        });
        let h = fibref::cases::parse_header(Path::new("x.fib"), &text).expect("the header parses");
        assert_eq!(
            h.verdict,
            fibref::cases::Verdict::Accept {
                result: fibref::cases::Expected::Int(3),
                audit: fibref::cases::AuditExpect::Clean,
                allocs: None,
            }
        );
    }
}
