#!/bin/bash
# Regenerates the results section of docs/shootout.md: runs scripts/shootout/run.sh (arguments are passed on:
# names, --size, --langs, -n) and replaces what lies between the markers
#   <!-- shootout:results:begin -->  and  <!-- shootout:results:end -->
# with the table, the machine and tool versions and the date. The prose of the report is not touched.
#   scripts/shootout/report.sh [run.sh arguments]           run, then write the report
#   scripts/shootout/report.sh --from rows.tsv              write the report from an earlier run's raw rows
# A run with a FAIL row still writes the report (the FAIL is in the table) and exits 1.
set -u
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
doc=$root/docs/shootout.md
scratch=${SHOOT_SCRATCH:-$HOME/.cache/fibber-shootout}
mkdir -p "$scratch"
tsv=$scratch/report-rows.tsv
status=0
if [ "${1:-}" = "--from" ]; then
  tsv=$2
else
  "$here/run.sh" "$@" --out "$tsv" > "$scratch/report-stdout.txt" || status=$?
  grep -E '^run.sh:' "$scratch/report-stdout.txt" >&2 || true
fi
fibc=${FIBC:-}
[ -z "$fibc" ] && [ -x "$root/bin/fibc" ] && fibc=$root/bin/fibc
[ -z "$fibc" ] && fibc=$(command -v fibc || true)
block=$scratch/report-block.md
{
  echo "<!-- shootout:results:begin -->"
  echo "Generated by \`scripts/shootout/report.sh\` on $(date -u +%Y-%m-%d), commit $(git -C "$root" rev-parse --short HEAD 2>/dev/null || echo unknown)."
  [ -n "${SHOOT_NOTE:-}" ] && echo "**$SHOOT_NOTE**" && echo
  echo "Machine: $(nproc) cores, $(awk -F: '/model name/ {print $2; exit}' /proc/cpuinfo | sed 's/^ //'), $(uname -sr)."
  echo "Tools: fibc $( [ -n "$fibc" ] && "$fibc" --version 2>&1 | head -1 ), $(java -version 2>&1 | head -1), $(gcc --version | head -1), $(basename "$(ls ${SHOOT_CLJ:-$HOME/.cache/fibber-scratch/B4-D/clj}/clojure-*.jar 2>/dev/null | head -1)")."
  echo
  "$here/run.sh" --render "$tsv"
  echo "<!-- shootout:results:end -->"
} > "$block"
if grep -q 'shootout:results:begin' "$doc"; then
  awk -v blk="$block" '
    /<!-- shootout:results:begin -->/ { while ((getline l < blk) > 0) print l; skip = 1; next }
    /<!-- shootout:results:end -->/ { skip = 0; next }
    !skip { print }' "$doc" > "$doc.new" && mv "$doc.new" "$doc"
else
  cat "$block" >> "$doc"
fi
echo "report.sh: wrote $doc from $tsv" >&2
exit $status
