#!/usr/bin/env python3
# Generates lib/fib/crypto/vectors-rsa.fib: the RSA keys (PKCS#8, with the SubjectPublicKeyInfo each has) and the RSASSA-PSS signatures that the RSA signing
# contract (lib/fib/crypto/contract-rsa.fib) uses. Run by scripts/gen-crypto-vectors-rsa.sh; python's `cryptography` (OpenSSL underneath) is the ORACLE here, as in
# gen_crypto_vectors_pk.py: it makes the keys, makes the PSS signatures (MGF1 with the same hash, salt length = digest length: RFC 8017 9.1 as TLS 1.3 rsae uses it),
# and every signature is verified by python again before it is written. Keys are generated here because the published sources (Wycheproof, RFC 8017) carry no
# private key with a PSS signing test: Wycheproof's PSS files are verify-only, and RFC 8017's own example key is 1024 bits, which a provider refuses (docs/design/crypto.md 9).
# PSS salts are random, so a signature is not a known answer for a SIGNER; it is one for a VERIFIER: the contract has the provider verify python's signatures, and verify
# its own (made with a key imported from the PKCS#8 here) under the SPKI python wrote. The output is committed; the gate and the drivers run fibber code only.
import os, sys
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import hashes, serialization as ser

OUT = os.environ["OUT"]
DER, PKCS8, NOENC, SPKI = ser.Encoding.DER, ser.PrivateFormat.PKCS8, ser.NoEncryption(), ser.PublicFormat.SubjectPublicKeyInfo
KEYS = [("rsa-2048-a", 2048), ("rsa-2048-b", 2048), ("rsa-3072", 3072), ("rsa-1024-refused", 1024)]
MSGS = [("empty", b""), ("abc", b"abc"), ("transcript-like-1000", bytes((i * 31 + 7) & 255 for i in range(1000)))]
SCHEMES = [("rsa-pss-sha256", hashes.SHA256()), ("rsa-pss-sha384", hashes.SHA384())]

def pss(h): return padding.PSS(mgf=padding.MGF1(h), salt_length=h.digest_size)
def q(s): return '"' + s + '"'

keys, signed = [], []
for ki, (name, bits) in enumerate(KEYS):
    k = rsa.generate_private_key(public_exponent=65537, key_size=bits)
    keys.append(f'(RsaKey {q(name)} {bits} {q(k.private_bytes(DER, PKCS8, NOENC).hex())} {q(k.public_key().public_bytes(DER, SPKI).hex())})')
    if bits < 2048: continue
    for sname, h in SCHEMES:
        for mname, m in MSGS:
            sig = k.sign(m, pss(h), h)
            k.public_key().verify(sig, m, pss(h), h)          # python accepts its own
            try:
                k.public_key().verify(sig, m + b"\0", pss(h), h); sys.exit("python accepted a changed message")
            except Exception as e:
                if e.__class__.__name__ != "InvalidSignature": raise
            signed.append(f'(RsaSigned :{sname} {ki} {q(mname)} {q(m.hex())} {q(sig.hex())})')

text = ";; fib.crypto.vectors-rsa: GENERATED by scripts/gen-crypto-vectors-rsa.sh (do not edit): RSA keys made by python's `cryptography` (PKCS#8 and the SubjectPublicKeyInfo of each)\n"
text += ";; and the RSASSA-PSS signatures it makes over fixed messages (MGF1 with the same hash, salt length = digest length), each verified by python before it is written.\n"
text += "(ns fib.crypto.vectors-rsa (:use fib.core fib.seq fib.coll))\n"
text += ";; RsaKey: `bits` is the modulus size; a key under 2048 bits is one a provider refuses. RsaSigned: `key` indexes `rsa-keys`, `msg` and `sig` are hex.\n"
text += "(defstruct RsaKey (name: str bits: i64 pkcs8: str spki: str))\n(defstruct RsaSigned (scheme: keyword key: i64 name: str msg: str sig: str))\n\n"
text += "(defun rsa-keys () -> (Vec RsaKey)\n  [" + "\n   ".join(keys) + "])\n\n"
text += "(defun rsa-signed () -> (Vec RsaSigned)\n  [" + "\n   ".join(signed) + "])\n"
open(f"{OUT}/vectors-rsa.fib", "w").write(text)
print(f"gen-crypto-vectors-rsa: {len(keys)} keys, {len(signed)} signatures")
