#!/usr/bin/env python3
"""Generate source-linked inventories, not invented release/stability guarantees."""
import argparse
import os
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]


def cell(value):
    return value.replace('|', '&#124;').replace('\n', ' ')


def references(fibc):
    pages = {}
    help_text = subprocess.check_output([fibc, '--help'], cwd=ROOT).decode()
    pages['docs/reference/cli.md'] = (
        '# CLI reference\n\nGenerated by `make doc-reference` from `fibc --help`. '
        'The documentation gate requires exact equality.\n\n```text\n'
        + help_text + '```\n')
    targets = subprocess.check_output([fibc, 'targets'], cwd=ROOT).decode().splitlines()
    rows = [line.split('\t') for line in targets]
    selected = [0, 22, 23]
    pages['docs/reference/targets.md'] = (
        '# Compiler targets\n\nGenerated from `fibc targets`; see '
        '[platform evidence](../policy/platform-support.md) before deployment.\n\n'
        '| ' + ' | '.join(rows[0][i] for i in selected) + ' |\n|---|---|---|\n'
        + ''.join('| ' + ' | '.join(cell(row[i]) for i in selected) + ' |\n'
                  for row in rows[1:]))
    env = {}
    for base in ['compiler', 'lib', 'rt']:
        for f in sorted((ROOT / base).rglob('*')):
            if f.suffix not in {'.fib', '.lir', '.c', '.h', '.mjs', '.js'}:
                continue
            # Inventory string constants, matching the audit's census. Test-only
            # and write-only constants are labelled by their source, not promised knobs.
            for n, line in enumerate(f.read_text(errors='replace').splitlines(), 1):
                for name in re.findall(r'"((?:FIB|FIBBER)_[A-Z0-9_]+)"', line):
                    env.setdefault(name, []).append((f.relative_to(ROOT), n))
    text = ('# Environment variable inventory\n\nGenerated from quoted constants in '
            '`compiler`, `lib` and `rt`. Entries include test/driver output knobs; '
            'presence is not a supported configuration promise. Follow the first '
            'source use for defaults and accepted values.\n\n'
            '`FIB_LIB` adds module roots; `FIBBER_HOME` selects the package cache. '
            '`FIB_TARGET_CPU`/`FIB_TARGET_TRIPLE` choose code generation, '
            '`FIB_VECTOR_BITS` overrides SIMD width, and `FIB_THREADS` chooses '
            'pool size. Static/C builds also use `FIB_MUSL_DIR` and `FIB_CC`.\n\n'
            '| Name | First source occurrence |\n|---|---|\n')
    for name, uses in sorted(env.items()):
        path, line = uses[0]
        text += f'| `{name}` | [{path}:{line}](../../{path}#L{line}) |\n'
    pages['docs/reference/environment.md'] = text
    text = ('# Builtin signatures\n\nGenerated from the maintained '
            '[stage-2 table](../../compiler/types/builtins.fib). This lists signatures, '
            'bounds and unsafe requirements, not all checker special forms. '
            'Stability classes and “since” versions have not been approved or '
            'recorded per export; they are deliberately not inferred.\n\n'
            '| Name | Signature | Bounds | Unsafe only |\n|---|---|---|---|\n')
    pattern = r'\(BuiltinSig "([^"]+)" "([^"]*)" "([^"]*)" \[[^\]]*\] (true|false)\)'
    source = (ROOT / 'compiler/types/builtins.fib').read_text()
    for name, sig, bounds, unsafe in re.findall(pattern, source):
        text += f'| `{name}` | `{cell(sig)}` | `{cell(bounds)}` | {unsafe} |\n'
    if len(re.findall(pattern, source)) != source.count('(BuiltinSig "'):
        raise ValueError('unparsed BuiltinSig row')
    pages['docs/reference/builtins.md'] = text
    pages.update(library())
    return pages


def library():
    """Index declarations and export-from chains; source links hold full types.

    These are declaration inventories, explicitly not typechecker schemes.
    Restrict matching to column-zero definitions to avoid bodies/templates.
    """
    modules = {}
    for f in sorted((ROOT / 'lib').rglob('*.fib')):
        source = f.read_text(errors='replace')
        namespace = re.search(r'^\(ns ([^\s()]+)', source, re.M)
        if namespace:
            modules[namespace[1]] = (f, source)

    def declarations(name, seen):
        if name in seen:
            return []
        seen.add(name)
        if name not in modules:
            raise ValueError(f'missing re-exported module: {name}')
        f, source = modules[name]
        found = []
        starts = list(re.finditer(r'^\((defun|defn|defmacro|defstruct|defrecord|defenum|defprotocol|def)\s+([^\s():]+)', source, re.M))
        for i, match in enumerate(starts):
            end = starts[i + 1].start() if i + 1 < len(starts) else len(source)
            # Privacy belongs to the declaration, before its body. A private
            # occurrence on a following comment/definition must not hide this one.
            header = source[match.start():end].split('\n\n', 1)[0]
            first = header.splitlines()[0]
            if ':private' in first:
                continue
            line = source.count('\n', 0, match.start()) + 1
            found.append((match[2], match[1], f.relative_to(ROOT), line))
        for chain in re.findall(r'\(:export-from\s+([^)]*)\)', source):
            for target in chain.split():
                found.extend(declarations(target, seen))
        return found

    facades = sorted({re.search(r'^\(ns ([^\s()]+)', f.read_text(), re.M)[1]
                      for f in (ROOT / 'lib/fib').glob('*.fib')}
                     | {name for name, (_, source) in modules.items() if '(:export-from' in source}
                     | ({'fib.json.schema', 'fib.logic.fd', 'fib.test.core', 'fib.test.run',
                         'fib.db.contract', 'fib.db.memory', 'fib.gpu.device', 'fib.gpu.sim',
                         'fib.gpu.contract', 'fib.view.tiles'} & modules.keys()))
    pages = {}
    index = ('# Library facade index\n\nGenerated from facade declarations and '
             '`export-from` chains. Follow source links for complete signatures, '
             'overloads, fields, variants and protocol methods. This is a declaration '
             'inventory, not inferred type schemes or a promise that every name in '
             'the stdlib plan is bound. Private declarations are omitted.\n\n'
             'All exports are pre-1.0; proposed S/E/I classes and “since” versions '
             'await explicit release decisions/metadata. External GraphQL, HOCON, '
             'database and GPU drivers are not bundled.\n\n'
             '| Module | Public declarations |\n|---|---|\n')
    for facade in facades:
        entries = sorted(set(declarations(facade, set())))
        filename = facade + '.md'
        index += f'| [{facade}]({filename}) | {len(entries)} |\n'
        f, _ = modules[facade]
        text = (f'# {facade}\n\nGenerated declaration inventory of '
                f'[{facade}](../../../{f.relative_to(ROOT)}). '
                'Source links contain the full signatures and API comments; '
                'enum variants and protocol methods belong to their linked declaration.\n\n'
                '| Name | Declaration | Defined in |\n|---|---|---|\n')
        for name, kind, path, line in entries:
            text += f'| `{cell(name)}` | {kind} | [{path}:{line}](../../../{path}#L{line}) |\n'
        pages['docs/reference/library/' + filename] = text
    pages['docs/reference/library/INDEX.md'] = index
    return pages


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--fibc', default=os.environ.get('FIBC', 'build/F'))
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    fibc = str(Path(args.fibc).resolve())
    pages = references(fibc)
    failures = []
    for path, text in pages.items():
        f = ROOT / path
        if args.check:
            if not f.exists() or f.read_text() != text:
                failures.append(path)
        else:
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(text)
    stale = set((ROOT / 'docs/reference/library').glob('fib.*.md')) - {ROOT / p for p in pages}
    failures.extend(str(p.relative_to(ROOT)) + ' (stale facade)' for p in stale)
    if failures:
        raise SystemExit('reference drift; run make doc-reference:\n' + '\n'.join(failures))
    print(f'references: {len(pages)} pages {"match" if args.check else "generated"}')


if __name__ == '__main__':
    main()
