#!/bin/bash
# Generates lib/fib/tls/roots.fib: the Mozilla root store as DATA (the base64 of each root certificate), from the curl project's PEM extract of Mozilla's list. The source is
# the DATED file named below, fetched into scratch and checked against the sha256 recorded here and in scripts/tls-roots.sha256 (ADR 0020): a changed upstream file is an
# error, never a silent update. The generated file is COMMITTED (about 200 KB of data): fibber has no build step to make it at build time, and an offline gate and a scratch
# image with no /etc/ssl need it as a file. To update the roots: pick a newer dated file at https://curl.se/ca/, change DATE and SHA256, run this, read the diff.
#   scripts/gen-tls-roots.sh [DEST]      (default DEST ~/.cache/fibber-scratch/tools/tls-roots)
set -eu
DATE=2026-09-25
SHA256=a41b5d356aea97a529fe27e0f7316d2f9d946d75927476cf9cf1b90637d00505
here=$(cd "$(dirname "$0")" && pwd)
dest=${1:-$HOME/.cache/fibber-scratch/tools/tls-roots}
mkdir -p "$dest"
pem="$dest/cacert-$DATE.pem"
[ -s "$pem" ] || curl -sSfL -m 120 -o "$pem" "https://curl.se/ca/cacert-$DATE.pem"
echo "$SHA256  $pem" | sha256sum -c --quiet - || { echo "gen-tls-roots: $pem does not match the pinned sha256 $SHA256" >&2; exit 1; }
echo "$SHA256  cacert-$DATE.pem" > "$here/tls-roots.sha256"
python3 - "$pem" "$here/../lib/fib/tls/roots.fib" "$DATE" "$SHA256" <<'EOF'
import sys, re
pem, out, date, sha = sys.argv[1:5]
text = open(pem).read()
blocks = re.findall(r"-----BEGIN CERTIFICATE-----\s*([A-Za-z0-9+/=\s]+?)\s*-----END CERTIFICATE-----", text)
blocks = ["".join(b.split()) for b in blocks]
per = 40
parts = [blocks[i:i + per] for i in range(0, len(blocks), per)]
with open(out, "w") as f:
    f.write(";; fib.tls.roots: GENERATED by scripts/gen-tls-roots.sh (do not edit). The Mozilla root store as data: %d root certificates, the curl project's extract dated %s\n" % (len(blocks), date))
    f.write(";; (https://curl.se/ca/cacert-%s.pem, sha256 %s). Each entry is the base64 of one DER certificate. `embedded-roots` parses them into a trust store: a scratch image with\n" % (date, sha))
    f.write(";; no /etc/ssl, an offline gate and a program that must not depend on the machine's files use it. Trust is a policy: this is Mozilla's, as of that date, and ages; the\n")
    f.write(";; caller decides whether to use it, a PEM file, or a store of its own. A root that does not parse makes `embedded-roots` an error (a store that silently lost a root is another store).\n")
    f.write("(ns fib.tls.roots (:use fib.core fib.seq fib.coll fib.tls.types fib.tls.pem) (:require [fib.crypto :as c]))\n")
    for n, p in enumerate(parts):
        f.write("(defun roots-%d :private () -> (Vec str)\n  [" % n)
        f.write("\n   ".join('"%s"' % b for b in p))
        f.write("])\n")
    expr = "(roots-0)"
    for n in range(1, len(parts)):
        expr = "(concat %s (roots-%d))" % (expr, n)
    f.write("(defun roots-b64 () -> (Vec str)\n  (vec %s))\n" % expr)
    f.write("(defun roots-count () -> i64 %d)\n" % len(blocks))
    f.write("(defun decode-all :private (xs: (Vec str)) -> (Result (Vec (Array i8)) TlsError)\n")
    f.write("  (loop [i 0 acc []]\n    (if (= i (count xs)) (Ok acc)\n      (match (c/unbase64 (nth xs i)) ((Err _) (Err (parse-err \"fib.tls.roots: an embedded root is not base64\"))) ((Ok d) (recur (+ i 1) (conj acc d)))))))\n")
    f.write("(defun embedded-roots () -> (Result TrustStore TlsError)\n  (match (decode-all (roots-b64)) ((Err e) (Err e)) ((Ok ders) (trust-from-ders ders))))\n")
print("wrote %d roots in %d parts" % (len(blocks), len(parts)))
EOF
