#!/usr/bin/env python3
# Generates the Unicode tables of the explicit modules fib.string.unicode.data and fib.regex.unicode.scripts from the pinned Unicode 16.0.0
# files (scripts/fetch-unicode.sh downloads them and checks specs/unicode-16.0.0.sha256, ADR 0020). Usage: scripts/gen-unicode.py DIR
# where DIR holds UnicodeData.txt SpecialCasing.txt PropList.txt Scripts.txt. Writes lib/fib/string/unicode/data.fib and
# lib/fib/regex/unicode/scripts.fib (generated: do not edit).
#
# Every table is ONE string literal inside a function (no top-level def: a table in a def costs every program that links the module, the
# FOLLOWUP-1 lesson), of fixed-width ASCII records sorted by their first field, so a lookup is a binary search over `str-byte-at`
# (no allocation, no state):
#   gc      8 bytes: start (6 hex), category (2 letters); a record runs to the next record's start; gaps are "Cn"
#   upper   12 bytes: code point (6 hex), simple uppercase mapping (6 hex); lower likewise
#   special 42 bytes: code point (6 hex), the full lowercase (3 x 6 hex, 000000 pads) and the full uppercase (3 x 6 hex): SpecialCasing.txt entries
#           that carry no condition and differ from the simple mapping
#   props   12 bytes: start (6 hex), end (6 hex) of Other_Uppercase / Other_Lowercase (PropList.txt)
#   scripts 8 bytes: start (6 hex), script index (2 hex) into the names string; index 0 is Unknown (Zzzz)
import sys, os, re

d = sys.argv[1]
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')

def hx(n): return '%06x' % n

# ---- UnicodeData.txt
gc = {}          # cp -> category
upper = {}
lower = {}
first = None
for line in open(os.path.join(d, 'UnicodeData.txt'), encoding='utf-8'):
    f = line.rstrip('\n').split(';')
    cp = int(f[0], 16)
    name, cat = f[1], f[2]
    if name.endswith(', First>'):
        first = cp
        continue
    if name.endswith(', Last>'):
        for c in range(first, cp + 1):
            gc[c] = cat
        continue
    gc[cp] = cat
    if f[12]: upper[cp] = int(f[12], 16)
    if f[13]: lower[cp] = int(f[13], 16)

recs = []
prev = None
for cp in range(0x110000):
    c = gc.get(cp, 'Cn')
    if c != prev:
        recs.append(hx(cp) + c)
        prev = c
gc_text = ''.join(recs)

def pairs(m): return ''.join(hx(k) + hx(v) for k, v in sorted(m.items()))

# ---- SpecialCasing.txt: the unconditional entries
special = {}
for line in open(os.path.join(d, 'SpecialCasing.txt'), encoding='utf-8'):
    line = line.split('#')[0].strip()
    if not line: continue
    f = [x.strip() for x in line.split(';')]
    if len(f) < 5 or f[4] != '': continue   # a condition list: skipped
    cp = int(f[0], 16)
    lo = [int(x, 16) for x in f[1].split()]
    up = [int(x, 16) for x in f[3].split()]
    if lo == [lower.get(cp, cp)] and up == [upper.get(cp, cp)]: continue
    special[cp] = (lo, up)
def trip(l): return ''.join(hx(x) for x in l) + '000000' * (3 - len(l))
special_text = ''.join(hx(cp) + trip(lo) + trip(up) for cp, (lo, up) in sorted(special.items()))

# ---- PropList.txt: Other_Uppercase, Other_Lowercase
props = {'Other_Uppercase': [], 'Other_Lowercase': []}
for line in open(os.path.join(d, 'PropList.txt'), encoding='utf-8'):
    line = line.split('#')[0].strip()
    if not line: continue
    r, p = [x.strip() for x in line.split(';')]
    if p in props:
        a, _, b = r.partition('..')
        props[p].append((int(a, 16), int(b or a, 16)))
def ranges(l): return ''.join(hx(a) + hx(b) for a, b in sorted(l))

def lit(s): return '"' + s + '"'

out = [';; fib.string.unicode.data: GENERATED by scripts/gen-unicode.py from Unicode 16.0.0 (do not edit; scripts/fetch-unicode.sh pins the files by sha256).',
       ';; Each table is one string literal of fixed-width ASCII records in a function (never a top-level def: nothing is allocated, and a program that',
       ';; does not require this module, or does not reach a function, pays nothing). The record layouts are in scripts/gen-unicode.py; fib.string.unicode',
       ';; reads them by binary search over `str-byte-at`.',
       '(ns fib.string.unicode.data)', '']
for name, text, doc in [
        ('gc-table', gc_text, 'start (6 hex) and general category (2 letters), %d runs' % len(recs)),
        ('upper-table', pairs(upper), 'code point and simple uppercase mapping, 12 bytes each, %d entries' % len(upper)),
        ('lower-table', pairs(lower), 'code point and simple lowercase mapping, 12 bytes each, %d entries' % len(lower)),
        ('special-table', special_text, 'unconditional SpecialCasing entries, 42 bytes each, %d entries' % len(special)),
        ('other-upper-table', ranges(props['Other_Uppercase']), 'Other_Uppercase ranges, 12 bytes each'),
        ('other-lower-table', ranges(props['Other_Lowercase']), 'Other_Lowercase ranges, 12 bytes each')]:
    out.append(';; %s' % doc)
    out.append('(defun %s () -> str' % name)
    out.append('  %s)' % lit(text))
    out.append('')
open(os.path.join(root, 'lib/fib/string/unicode/data.fib'), 'w').write('\n'.join(out))

# ---- Scripts.txt
names = ['Unknown']
sc = []
for line in open(os.path.join(d, 'Scripts.txt'), encoding='utf-8'):
    line = line.split('#')[0].strip()
    if not line: continue
    r, n = [x.strip() for x in line.split(';')]
    a, _, b = r.partition('..')
    if n not in names: names.append(n)
    sc.append((int(a, 16), int(b or a, 16), names.index(n)))
sc.sort()
srecs = []
prev = None
cur = 0
for a, b, i in sc:
    if a > cur: srecs.append((cur, 0))
    srecs.append((a, i))
    cur = b + 1
if cur <= 0x10ffff: srecs.append((cur, 0))
merged = []
for a, i in srecs:
    if merged and merged[-1][1] == i: continue
    merged.append((a, i))
stext = ''.join(hx(a) + '%02x' % i for a, i in merged)
out = [';; fib.regex.unicode.scripts: GENERATED by scripts/gen-unicode.py from Unicode 16.0.0 Scripts.txt (do not edit).',
       ';; `script-table`: 8-byte records, start (6 hex) and the index (2 hex) of the script in `script-names` (0 is Unknown), %d runs; `script-names`: the long' % len(merged),
       ';; script names, comma separated, in index order. String literals inside functions: nothing is allocated until a pattern uses \\p{Script=..}.',
       '(ns fib.regex.unicode.scripts)', '',
       '(defun script-table () -> str', '  %s)' % lit(stext), '',
       '(defun script-names () -> str', '  %s)' % lit(','.join(names)), '']
open(os.path.join(root, 'lib/fib/regex/unicode/scripts.fib'), 'w').write('\n'.join(out))
print('gc runs', len(recs), 'upper', len(upper), 'lower', len(lower), 'special', len(special), 'script runs', len(merged), 'scripts', len(names))
