#!/usr/bin/env python3
"""Writes specs/json-floats-spec.fib: a few hundred parse cases (text -> exact bits, from Python's correctly rounded float()) and print cases
(bits -> the text fib.json must write, from Python's repr digits laid out by the writer's rules). The cases are the hard ones: halfway points
between doubles, the nudged neighbours, subnormals, boundaries, 17-digit ties, powers of two, powers of ten. The full-size runs (millions of cases)
are scripts/json-floats.sh. usage: scripts/gen-json-floats-spec.py > specs/json-floats-spec.fib"""
import random, struct, sys
from decimal import Decimal, getcontext
from fractions import Fraction
getcontext().prec = 1200
rnd = random.Random(7)
bits = lambda x: struct.unpack('<Q', struct.pack('<d', x))[0]
frombits = lambda b: struct.unpack('<d', struct.pack('<Q', b))[0]
sgn = lambda b: b - (1 << 64) if b >= (1 << 63) else b

def layout(x):  # the writer's text for x (finite, nonzero), from repr's digits
    r = repr(abs(x)); m, _, e = r.partition('e'); e = int(e) if e else 0
    ip, _, fp = m.partition('.'); digits = (ip + fp).lstrip('0'); exp = e - len(fp)
    while digits.endswith('0') and len(digits) > 1: digits = digits[:-1]; exp += 1
    n = len(digits); E = exp + n - 1
    if 0 <= E < 17:
        t = digits + '0' * (E + 1 - n) + '.0' if n <= E + 1 else digits[:E + 1] + '.' + digits[E + 1:]
    elif -5 <= E < 0:
        t = '0.' + '0' * (-E - 1) + digits
    else:
        t = digits[0] + ('.' + digits[1:] if n > 1 else '') + 'e' + ('-' if E < 0 else '') + str(abs(E))
    return ('-' if x < 0 else '') + t

parse_cases = []
for t in ['5e-324', '2.4703282292062327e-324', '2.4703282292062328e-324', '2.2250738585072014e-308', '2.2250738585072011e-308', '1.7976931348623157e308',
          '9007199254740993', '9007199254740992.5', '0.1', '2.5e-5', '8.41e21', '123456789012345678', '1e23', '1e22']:
    parse_cases.append(t)
for i in range(120):
    b = [rnd.getrandbits(63), rnd.getrandbits(52), (rnd.randrange(1, 2046) << 52), (1023 + rnd.randrange(-60, 60)) << 52 | rnd.getrandbits(52)][i % 4]
    d = frombits(b)
    if d != d or d == float('inf') or b >= 0x7FEFFFFFFFFFFFFF: continue
    nxt = frombits(b + 1); m = (Fraction(d) + Fraction(nxt)) / 2
    dec = Decimal(m.numerator) / Decimal(m.denominator)
    parse_cases.append(str(dec).replace('E+', 'e').replace('E-', 'e-'))
    parse_cases.append(str(dec + Decimal(10) ** (dec.adjusted() - 40)).replace('E+', 'e').replace('E-', 'e-'))
    parse_cases.append(str(dec - Decimal(10) ** (dec.adjusted() - 40)).replace('E+', 'e').replace('E-', 'e-'))
    parse_cases.append('%.17g' % d)
rows = []
for t in parse_cases:
    try: x = float(t)
    except OverflowError: continue
    if x == float('inf'): continue
    rows.append('   (Pair "%s" %d)' % (t, sgn(bits(x))))
prints = []
for i in range(150):
    b = [rnd.getrandbits(63), rnd.getrandbits(52), (rnd.randrange(1, 2046) << 52), bits(float(rnd.randrange(1, 10 ** 9)) / 10 ** rnd.randrange(0, 12)), bits(float(rnd.randrange(1, 2 ** 60)))][i % 5]
    x = frombits(b)
    if x != x or x == float('inf') or x == 0: continue
    prints.append('   (Pair %d "%s")' % (sgn(b), layout(x)))
for x in (5e-324, 1.7976931348623157e308, 1e21, 1e22, 100.0, 0.1, 1.5e-7, 0.00001234, 123456789012345680.0, 1e16, 12345678901234567.0, 2.0 ** 63, 0.3):
    prints.append('   (Pair %d "%s")' % (sgn(bits(x)), layout(x)))
sys.stdout.write(''';; GENERATED by scripts/gen-json-floats-spec.py (do not edit). Floats at the hard places (docs/design/json.md 3, 4): %d texts that must parse to exactly the bits
;; Python's correctly rounded float() gives (halfway points between doubles and their neighbours, subnormals, boundaries, 17-digit ties) and %d doubles that
;; must be written as exactly the shortest, closest text (Python's repr digits, the writer's layout). The millions-of-cases runs are scripts/json-floats.sh.
(ns main (:use fib.core fib.seq fib.coll fib.test.core fib.test.run fib.json.types fib.json.parse fib.json.write))

(defun parse-cases () -> (Vec (Pair str i64))
  [
%s
  ])

(defun print-cases () -> (Vec (Pair i64 str))
  [
%s
  ])

(defun bits-of (t: str) -> i64 (match (parse t) ((Ok (JFloat f)) (f64->bits f)) ((Ok (JInt i)) (f64->bits (double i))) (_ 0)))

(defspecs specs
  (feature "floats"
    (scenario "parse: exact bits at the hard cases"
      (then (expect = [] (vec (map (fn (c: (Pair str i64)) (. c fst)) (filter (fn (c: (Pair str i64)) (!= (bits-of (. c fst)) (. c snd))) (parse-cases)))))))
    (scenario "write: the shortest closest text at the hard cases"
      (then (expect = [] (vec (map (fn (c: (Pair i64 str)) (. c snd)) (filter (fn (c: (Pair i64 str)) (!= (write (JFloat (bits->f64 (. c fst)))) (. c snd))) (print-cases)))))))))

(defun main () -> i64 (run-main (specs)))
''' % (len(rows), len(prints), '\n'.join(rows), '\n'.join(prints)))
