#!/usr/bin/env python3
"""Generates lib/fib/json/pow10.fib: the table of Schubfach (Giulietti, "The Schubfach way to render doubles") for fib.json.dtoa.
For k in [-324, 292], g(k) = floor(10^-k * 2^(125 - floor(log2 10^-k))) + 1, a number in [2^125, 2^126), as two 63-bit words (high, low), hex text.
The shortest-digits algorithm and these constants are checked against Python's repr() by docs/shootout/json.md's commands (scripts/json-floats.sh)."""
import sys
KMIN, KMAX = -324, 292
FLOG2POW10 = lambda e: (e * 935039633142894) >> 48   # exact for |e| <= 400 (checked against big integers)
words = []
for k in range(KMIN, KMAX + 1):
    e = -k
    sh = 125 - FLOG2POW10(e)
    if e >= 0:
        g = (10 ** e) << sh if sh >= 0 else (10 ** e) >> (-sh)
    else:
        g = (1 << sh) // (10 ** -e)
    g += 1
    assert (1 << 125) <= g < (1 << 126)
    words.append(g >> 63)
    words.append(g & ((1 << 63) - 1))
out = [';; fib.json.pow10: GENERATED by scripts/gen-json-pow10.py (do not edit). The table g(k) of Schubfach for k from -324 to 292, two 63-bit words per k (high, low), as hex text decoded once at start.',
       '(ns fib.json.pow10 (:use fib.core fib.seq fib.coll))', '', '(defun pow10-hex () -> (Vec str)', '  [']
per = 64
for i in range(0, len(words), per):
    out.append('   "%s"' % ''.join('%016x' % w for w in words[i:i + per]))
out.append('  ])')
out.append('''
(defun hex-word (s: str at: i64) -> i64
  (loop [k 0 v 0]
    (if (= k 16) v
        (let [c (zext i64 (str-byte-at s (+ at k)))
              d (if (< c 58) (- c 48) (- c 87))]
          (recur (+ k 1) (bit-or (shl v 4) d))))))

(defun decode-table (chunks: (Vec str)) -> (Array i64)
  (let [out (cell (array %d 0))]
    (do (dotimes (c (count chunks))
          (let [s (nth chunks c)]
            (dotimes (i (quot (str-len s) 16)) (array-set! &out (+ (* c 64) i) (hex-word s (* i 16))))))
        @out)))

;; Entry k is at index 2 (k + 324): the high word, then the low word.
(def pow10: (Array i64) (decode-table (pow10-hex)))''' % len(words))
open(sys.argv[1] if len(sys.argv) > 1 else 'lib/fib/json/pow10.fib', 'w').write('\n'.join(out) + '\n')
print(len(words))
