#!/usr/bin/env python3
"""scripts/gen-lz4-vectors.py: writes lib/fib/compress/lz4/vectors.fib, the published test vectors of fib.compress.lz4, made by the REFERENCE: the lz4 v1.10.0 CLI (built by
scripts/fetch-lz4-tools.sh) for frames (every flag combination: -1..-12, -B4..-B7, -BI/-BD, --no-frame-crc, -BX, --content-size, a dictionary with -D, legacy -l, concatenated
and skippable frames) and python lz4.block (liblz4 1.10) for blocks. The inputs are given by recipe so the file stays small: hex:H, zeros:N, rep:HEX:N.
usage: gen-lz4-vectors.py [LZ4_CLI]   (the output is checked in: re-running it with the same tools gives the same file)"""
import subprocess, sys, os, tempfile, struct, random
import lz4.block as lb
CLI = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/.cache/fibber-scratch/tools/lz4/lz4-1.10.0/programs/lz4')
rng = random.Random(20261007)
WORDS = [b'the', b'of', b'and', b'compression', b'block', b'frame', b'literal', b'match', b'offset', b'token', b'stream', b'checksum', b'window']
def text(n):
    out = b''
    while len(out) < n: out += rng.choice(WORDS) + (b'.\n' if rng.random() < 0.1 else b' ')
    return out[:n]
def expand(r):
    k, *rest = r.split(':')
    if k == 'hex': return bytes.fromhex(rest[0])
    if k == 'zeros': return bytes(int(rest[0]))
    if k == 'rep': p = bytes.fromhex(rest[0]); n = int(rest[1]); return (p * (n // len(p) + 1))[:n]
INPUTS = [('empty', 'hex:'), ('one', 'hex:61'), ('text-3000', 'hex:' + text(3000).hex()), ('random-300', 'hex:' + bytes(rng.randrange(256) for _ in range(300)).hex()),
          ('zeros-100000', 'zeros:100000'), ('pattern3-70000', 'rep:010203:70000'), ('pattern-300-100000', 'rep:' + bytes(rng.randrange(256) for _ in range(300)).hex() + ':100000'),
          ('text-20000', 'hex:' + text(20000).hex())]
FLAGS = [[], ['-1'], ['-3'], ['-9'], ['-12'], ['-B4'], ['-B5', '-BD'], ['-B6', '-BI'], ['-B7', '-BD'], ['-BI', '--no-frame-crc'], ['-BX'], ['-BD', '-BX', '--no-frame-crc'],
         ['--content-size'], ['--content-size', '-B4', '-BI'], ['-9', '--content-size', '-BX']]
def run(args, data, extra=()):
    with tempfile.TemporaryDirectory() as d:
        i = os.path.join(d, 'in'); o = os.path.join(d, 'out'); open(i, 'wb').write(data)
        subprocess.run([CLI, '-q', '-f', *args, *extra, i, o], check=True, capture_output=True); return open(o, 'rb').read()
lines = [';; GENERATED by scripts/gen-lz4-vectors.py from the lz4 v1.10.0 CLI and python lz4.block (liblz4 1.10): published vectors for fib.compress.lz4. DO NOT EDIT.',
         ';; `inputs`: [name recipe] (hex:H, zeros:N, rep:HEX:N, the pattern repeated to N bytes; cat:a+b the inputs a and b one after the other). `frame-vectors`: (name input-name compressed-hex dictionary-input-name or \"\"); `block-vectors`: [name input-name block-hex].',
         '(ns fib.compress.lz4.vectors (:use fib.core fib.seq fib.coll))', '(defstruct LzVector (name: str input: str compressed: str dict: str))', '']
fv = []
for iname, rec in INPUTS:
    data = expand(rec)
    for fl in (FLAGS if len(data) < 15000 or iname.startswith(('zeros', 'pattern3')) else [[], ['-9'], ['-B4', '-BD'], ['-BX']]):
        fv.append(('%s %s' % (iname, ' '.join(fl) or 'default'), iname, run(fl, data).hex(), ''))
# a dictionary: the first 2000 bytes of the text-20000 input, used by -D
dictdata = expand(INPUTS[-1][1])[:2000]
with tempfile.TemporaryDirectory() as d:
    dp = os.path.join(d, 'dict'); open(dp, 'wb').write(dictdata)
    for iname, rec in INPUTS[2:6]:
        for fl in ([], ['-9'], ['-BD'], ['-BI']):
            fv.append(('%s -D %s' % (iname, ' '.join(fl) or 'default'), iname, run(fl, expand(rec), ['-D', dp]).hex(), 'dict'))
# legacy frames
for iname, rec in INPUTS[:6]:
    fv.append(('%s legacy' % iname, iname, run(['-l'], expand(rec)).hex(), ''))
# concatenated frames and a skippable frame: the CLI concatenates; skippable is built by hand (magic 0x184D2A50, size, payload)
a, b = expand(INPUTS[2][1]), expand(INPUTS[4][1])
fv.append(('concatenated text-3000 + zeros-100000', 'cat:text-3000+zeros-100000', (run([], a) + run(['-9'], b)).hex(), ''))
skip = struct.pack('<II', 0x184D2A55, 5) + b'12345'
fv.append(('skippable then frame', 'cat:text-3000', (skip + run([], a) + skip).hex(), ''))
lines.append('(defun inputs () -> (Vec (Vec str))\n  [' + '\n   '.join('["%s" "%s"]' % (n, r) for n, r in INPUTS + [('dict', 'hex:' + dictdata.hex())]) + '])\n')
def chunked(name, ty, items, fmt):
    parts = [items[i:i + 30] for i in range(0, len(items), 30)]
    for k, part in enumerate(parts):
        lines.append('(defun %s-%d () -> (Vec %s)\n  [' % (name, k, ty) + '\n   '.join(fmt(x) for x in part) + '])\n')
    lines.append('(defun %s () -> (Vec %s)\n  (reduce (fn (a: (Vec %s) b: (Vec %s)) (into a b)) [] [%s]))\n' % (name, ty, ty, ty, ' '.join('(%s-%d)' % (name, k) for k in range(len(parts)))))
chunked('frame-vectors', 'LzVector', fv, lambda v: '(LzVector "%s" "%s" "%s" "%s")' % v)
bv = []
for iname, rec in INPUTS:
    data = expand(rec)
    for mode, lv, ac in [('fast', 0, 1), ('fast', 0, 8), ('high_compression', 3, 1), ('high_compression', 9, 1), ('high_compression', 12, 1)]:
        bv.append(('%s %s %s' % (iname, mode, ac if mode == 'fast' else lv), iname, lb.compress(data, mode=mode, acceleration=ac, compression=lv or 9, store_size=False).hex()))
chunked('block-vectors', '(Vec str)', bv, lambda v: '["%s" "%s" "%s"]' % v)
open(os.path.join(os.path.dirname(__file__), '..', 'lib/fib/compress/lz4/vectors.fib'), 'w').write('\n'.join(lines) + '\n')
print(len(fv), 'frame vectors', len(bv), 'block vectors')
