#!/usr/bin/env python3
# Generates lib/fib/json/pow5.fib: the 128-bit truncated powers of five for q in [-342, 308] (Lemire's table of fast_float / Eisel-Lemire),
# two 64-bit words per q (high then low), as hex text that fib.json.pow5 decodes at start.
import sys
W = 'lib/fib/json/pow5.fib'
words = []
for q in range(-342, 309):
    if q < 0:
        p5 = 5 ** (-q)
        z = 0
        while (1 << z) < p5:
            z += 1
        if q >= -27:
            c = (2 ** (z + 127)) // p5 + 1
        else:
            c = (2 ** (2 * z + 2 * 64)) // p5 + 1
            while c >= (1 << 128):
                c //= 2
    else:
        c = 5 ** q
        while c < (1 << 127):
            c *= 2
        while c >= (1 << 128):
            c //= 2
    words.append(c >> 64)
    words.append(c & ((1 << 64) - 1))
chunks = []
per = 64
for i in range(0, len(words), per):
    chunks.append(''.join('%016x' % w for w in words[i:i + per]))
out = [';; fib.json.pow5: GENERATED by scripts/gen-json-pow5.py (do not edit). The truncated 128-bit powers of five, q from -342 to 308, two words per q.',
       ';; Hex text, decoded once at start into an array of i64 (the high word of 5^q normalised to 128 bits, then the low word); the Eisel-Lemire float parser indexes it.',
       '(ns fib.json.pow5 (:use fib.core fib.seq fib.coll))', '', '(defun pow5-hex () -> (Vec str)', '  [']
for c in chunks:
    out.append('   "%s"' % c)
out.append('  ])')
out.append('''
(defun hex-word (s: str at: i64) -> i64
  (loop [k 0 v 0]
    (if (= k 16) v
        (let [c (zext i64 (str-byte-at s (+ at k)))
              d (if (< c 58) (- c 48) (- c 87))]
          (recur (+ k 1) (bit-or (shl v 4) d))))))

(defun decode-table (chunks: (Vec str)) -> (Array i64)
  (let [out (cell (array 1302 0))]
    (do (dotimes (c (count chunks))
          (let [s (nth chunks c)]
            (dotimes (i (quot (str-len s) 16)) (array-set! &out (+ (* c 64) i) (hex-word s (* i 16))))))
        @out)))

(def pow5: (Array i64) (decode-table (pow5-hex)))''')
open(sys.argv[1] if len(sys.argv) > 1 else W, 'w').write('\n'.join(out) + '\n')
print(len(words))
